enum ErrorTypes {
  REDIS_CONNECTION_ERROR = 'REDIS_CONNECTION_ERROR',
  QUEUE_ERROR = 'QUEUE_ERROR',
  PAYLOAD_ERROR = 'PAYLOAD_ERROR',
  CONSUMER_GROUP_ERROR = 'CONSUMER_GROUP_ERROR',
  CONSUMER_ERROR = 'CONSUMER_ERROR',
  MESSAGE_ID_ERROR = 'MESSAGE_ID_ERROR',
}

export default ErrorTypes;
